image: sds-ubuntu-14.04:1.9-rc0

variables:
  OS_DEPLOY_CI_RUNNER_IP: '17.18.99.1'

stages:
  - test-unit
  - test-integ

unit-test:
  stage: test-unit
  script:
    - cd $HOME
    - apt update
    - apt install -y python-pip
    - apt install -y python-setuptools
    - pip install wheel
    - apt install -y jq
    - pip install yq
    - wget -O /tmp/bats.tar.gz https://github.com/sstephenson/bats/archive/v0.4.0.tar.gz
    - tar -C /tmp -xzf /tmp/bats.tar.gz
    - cd /tmp/bats-*
    - ./install.sh /usr
    - cd ${CI_PROJECT_DIR}
    - tests/unit_tests/run
  tags:
    - unit-tests

ubuntu16.04-qcow2:
  stage: test-integ
  variables:
    CONFIG_FILE_NAME: SheepCfg_ubuntu16_04_qcow2.yml
    EXPECTED_UNAME: 'Linux ubuntu 4.4.0-170-generic'
    EXTRA_KERNEL_CMDLINE: console=ttyS1,57600n8
  script:
    - cd ${CI_PROJECT_DIR}
    - tests/integration_test/run
  tags:
    - integration

centos7-qcow2:
  stage: test-integ
  variables:
    CONFIG_FILE_NAME: SheepCfg_centos7_qcow2.yml
    EXPECTED_UNAME: 'Linux localhost.localdomain 3.10.0-957.27.2.el7.x86_64'
    EXTRA_KERNEL_CMDLINE: console=ttyS1,57600n8
  script:
    - cd ${CI_PROJECT_DIR}
    - tests/integration_test/run
  tags:
    - integration

debian9-qcow2:
  stage: test-integ
  variables:
    CONFIG_FILE_NAME: SheepCfg_debian9_qcow2.yml
    EXPECTED_UNAME: 'Linux debian.example.com 4.9.0-11-amd64'
    EXTRA_KERNEL_CMDLINE: console=ttyS1,57600n8
  script:
    - cd ${CI_PROJECT_DIR}
    - tests/integration_test/run
  tags:
    - integration

opensuse15.1-qcow2:
  stage: test-integ
  variables:
    CONFIG_FILE_NAME: SheepCfg_opensuse15_1_qcow2.yml
    EXPECTED_UNAME: 'Linux localhost 4.12.14-lp151.28.36-default'
    EXTRA_KERNEL_CMDLINE: console=ttyS1,57600n8
  script:
    - cd ${CI_PROJECT_DIR}
    - tests/integration_test/run
  tags:
    - integration
