image: sesame-ubuntu-14.04:1.11

variables:
  OS_DEPLOY_CI_RUNNER_IP: '17.18.99.1'

stages:
  - test-unit
  - code-style
  - test-integ

unit-test:
  stage: test-unit
  script:
    - cd ${CI_PROJECT_DIR}
    - tests/unit_tests/run
  tags:
    - unit-tests

code-formatting:
  stage: code-style
  script:
    - cd ${CI_PROJECT_DIR}
    - shfmt -sr -i 0 -d os-install.sh tests/unit_tests/run tests/integration_test/run
  tags:
    - unit-tests

ubuntu16.04-qcow2-uefi_boot:
  stage: test-integ
  variables:
    CONFIG_FILE_NAME: SheepCfg_ubuntu16_04_qcow2_leo.yml
    EXPECTED_UNAME: 'Linux ubuntu 4.4.0-173-generic'
    EXTRA_KERNEL_CMDLINE: console=ttyS1,57600n8
  script:
    - cd ${CI_PROJECT_DIR}
    - tests/integration_test/run
  artifacts:
    when: always
    paths:
      - '*.cast'
  tags:
    - integration

centos7-qcow2-uefi_boot:
  stage: test-integ
  variables:
    CONFIG_FILE_NAME: SheepCfg_centos7_qcow2_leo.yml
    EXPECTED_UNAME: 'Linux localhost.localdomain 3.10.0-957.27.2.el7.x86_64'
    EXTRA_KERNEL_CMDLINE: console=ttyS1,57600n8
  script:
    - cd ${CI_PROJECT_DIR}
    - tests/integration_test/run
  artifacts:
    when: always
    paths:
      - '*.cast'
  tags:
    - integration

debian9-qcow2-uefi_boot:
  stage: test-integ
  variables:
    CONFIG_FILE_NAME: SheepCfg_debian9_qcow2_leo.yml
    EXPECTED_UNAME: 'Linux debian.example.com 4.9.0-11-amd64'
    EXTRA_KERNEL_CMDLINE: console=ttyS1,57600n8
  script:
    - cd ${CI_PROJECT_DIR}
    - tests/integration_test/run
  artifacts:
    when: always
    paths:
      - '*.cast'
  tags:
    - integration

opensuse15.1-qcow2-uefi_boot:
  stage: test-integ
  variables:
    CONFIG_FILE_NAME: SheepCfg_opensuse15_1_qcow2_leo.yml
    EXPECTED_UNAME: 'Linux localhost 4.12.14-lp151.28.36-default'
    EXTRA_KERNEL_CMDLINE: console=ttyS1,57600n8
  script:
    - cd ${CI_PROJECT_DIR}
    - tests/integration_test/run
  artifacts:
    when: always
    paths:
      - '*.cast'
  tags:
    - integration

ubuntu16.04-qcow2-legacy_boot:
  stage: test-integ
  variables:
    CONFIG_FILE_NAME: SheepCfg_ubuntu16_04_qcow2_win.yml
    EXPECTED_UNAME: 'Linux ubuntu 4.4.0-173-generic'
    EXTRA_KERNEL_CMDLINE: console=ttyS1,115200n8 iomem=relaxed ethdevice=enp12s0 module_blacklist=mei,mei_me
  script:
    - cd ${CI_PROJECT_DIR}
    - tests/integration_test/run
  artifacts:
    when: always
    paths:
      - '*.cast'
  tags:
    - integration-legacy

centos7-qcow2-legacy_boot:
  stage: test-integ
  variables:
    CONFIG_FILE_NAME: SheepCfg_centos7_qcow2_win.yml
    EXPECTED_UNAME: 'Linux localhost.localdomain 3.10.0-957.27.2.el7.x86_64'
    EXTRA_KERNEL_CMDLINE: console=ttyS1,115200n8 iomem=relaxed ethdevice=enp12s0 module_blacklist=mei,mei_me
  script:
    - cd ${CI_PROJECT_DIR}
    - tests/integration_test/run
  artifacts:
    when: always
    paths:
      - '*.cast'
  tags:
    - integration-legacy

debian9-qcow2-legacy_boot:
  stage: test-integ
  variables:
    CONFIG_FILE_NAME: SheepCfg_debian9_qcow2_win.yml
    EXPECTED_UNAME: 'Linux debian.example.com 4.9.0-11-amd64'
    EXTRA_KERNEL_CMDLINE: console=ttyS1,115200n8 iomem=relaxed ethdevice=enp12s0 module_blacklist=mei,mei_me
  script:
    - cd ${CI_PROJECT_DIR}
    - tests/integration_test/run
  artifacts:
    when: always
    paths:
      - '*.cast'
  tags:
    - integration-legacy

opensuse15.1-qcow2-legacy_boot:
  stage: test-integ
  variables:
    CONFIG_FILE_NAME: SheepCfg_opensuse15_1_qcow2_win.yml
    EXPECTED_UNAME: 'Linux localhost 4.12.14-lp151.28.36-default'
    EXTRA_KERNEL_CMDLINE: console=ttyS1,115200n8 iomem=relaxed ethdevice=enp12s0 module_blacklist=mei,mei_me
  script:
    - cd ${CI_PROJECT_DIR}
    - tests/integration_test/run
  artifacts:
    when: always
    paths:
      - '*.cast'
  tags:
    - integration-legacy
